# generated by datamodel-codegen:
#   filename:  input_schema.json
#   timestamp: 2024-05-13T11:54:25+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ChromaIntegration(BaseModel):
    chroma_collection_name: Optional[str] = Field(
        'chroma',
        description='Chroma DB collection name',
        title='Chroma DB collection name',
    )
    chroma_client_host: str = Field(
        ..., description='Host argument for ChromaDB HTTP Client', title='ChromaDB host'
    )
    chroma_client_port: Optional[int] = Field(
        8080,
        description='Port argument for ChromaDB HTTP Client',
        title='ChromaDB port',
    )
    chroma_client_ssl: Optional[bool] = Field(
        False, description='Enable/Disable SSL', title='ChromDB SSL'
    )
    chroma_server_auth_credentials: Optional[str] = Field(
        None,
        description='ChromaDB server Auth Static API token.',
        title='ChromaDB server auth Static API token credentials',
    )
    openai_api_key: str = Field(
        ..., description='OpenAI API KEY', title='OpenAI API KEY'
    )
    fields: List = Field(
        ...,
        description="Specify Dataset fields for text extraction in this array, using dot notation. \n\nE.g., for a crawler's 'text' output field, simply add 'text' to the array.",
        title='Fields',
    )
    metadata_fields: Optional[Dict[str, Any]] = Field(
        None,
        description='Select metadata fields (supports dot notation)',
        title='Metadata fields',
    )
    metadata_values: Optional[Dict[str, Any]] = Field(
        None,
        description='Custom values saved to db for every Dataset item as metadata',
        title='Metadata values',
    )
    perform_chunking: Optional[bool] = Field(
        False,
        description='If set to true, the resulting text will be chunked according to the settings below',
        title='Perform chunking',
    )
    chunk_size: Optional[int] = Field(
        1000,
        description='The maximum character length of each text chunk',
        ge=1,
        title='Chunk size',
    )
    chunk_overlap: Optional[int] = Field(
        0,
        description='The character overlap between text chunks that are next to each other',
        ge=0,
        title='Chunk overlap',
    )
    dataset_id: Optional[str] = Field(
        None,
        description='Dataset ID (when running standalone without integration)',
        title='Dataset ID',
    )
